window.SITE_DATA = {
  "site": {
    "title": "VIRUS FOTO",
    "heroText": "Фотография как история — живые эмоции, характер и свет.",
    "about": "Работаю в Челябинске и Челябинской области. Помогаю с позированием и собираю съёмку так, чтобы кадры оставались живыми и естественными."
  },
  "contacts": {
    "instagram": "https://www.instagram.com/virus_foto.lv?stkn=MTg1YXlmaGRiMTdhcw==",
    "telegram": "https://t.me/Verfluchter_Engel",
    "tgk": "https://t.me/VerfluchterEngel",
    "email": "Vovakulbakin1999@gmail.com",
    "phoneHref": "tel:+79777959689",
    "phoneText": "+7 (977) 795-96-89"
  },
  "prices": [
    {
      "name": "Индивидуальная",
      "price": "5 000 ₽",
      "note": "1 час"
    },
    {
      "name": "Love Story",
      "price": "6 000 ₽",
      "note": "1 час"
    },
    {
      "name": "Семейная",
      "price": "7 000 ₽",
      "note": "1 час"
    },
    {
      "name": "Коммерческая",
      "price": "от 6 000 ₽",
      "note": "за час"
    }
  ],
  "persons": [
    {
      "id": "fresh",
      "photos": [
        "assets/images/studio_015.webp",
        "assets/images/studio_016.webp",
        "assets/images/studio_017.webp",
        "assets/images/studio_018.webp",
        "assets/images/studio_019.webp",
        "assets/images/studio_020.webp",
        "assets/images/studio_021.webp",
        "assets/images/studio_022.webp",
        "assets/images/studio_023.webp",
        "assets/images/studio_024.webp",
        "assets/images/studio_025.webp",
        "assets/images/studio_026.webp",
        "assets/images/studio_027.webp",
        "assets/images/studio_028.webp",
        "assets/images/studio_029.webp",
        "assets/images/studio_030.webp",
        "assets/images/studio_031.webp",
        "assets/images/studio_032.webp",
        "assets/images/studio_033.webp",
        "assets/images/studio_034.webp",
        "assets/images/nature_016.webp",
        "assets/images/nature_017.webp",
        "assets/images/nature_018.webp",
        "assets/images/nature_019.webp",
        "assets/images/nature_020.webp",
        "assets/images/nature_021.webp",
        "assets/images/nature_022.webp",
        "assets/images/nature_023.webp",
        "assets/images/nature_024.webp",
        "assets/images/nature_025.webp",
        "assets/images/nature_026.webp",
        "assets/images/studio_005.webp",
        "assets/images/studio_006.webp",
        "assets/images/studio_007.webp",
        "assets/images/studio_008.webp",
        "assets/images/studio_009.webp",
        "assets/images/studio_010.webp",
        "assets/images/studio_011.webp",
        "assets/images/studio_012.webp",
        "assets/images/studio_013.webp",
        "assets/images/studio_014.webp"
      ],
      "cover": "assets/images/studio_015.webp",
      "isNew": true
    },
    {
      "id": "03",
      "photos": [
        "assets/images/nature_009.webp",
        "assets/images/nature_010.webp",
        "assets/images/nature_011.webp",
        "assets/images/nature_012.webp",
        "assets/images/nature_013.webp",
        "assets/images/nature_014.webp",
        "assets/images/nature_015.webp",
        "assets/images/city_001.webp",
        "assets/images/city_002.webp",
        "assets/images/city_003.webp",
        "assets/images/city_004.webp",
        "assets/images/city_005.webp",
        "assets/images/city_006.webp",
        "assets/images/city_007.webp",
        "assets/images/city_008.webp",
        "assets/images/city_009.webp",
        "assets/images/city_010.webp",
        "assets/images/city_011.webp"
      ],
      "cover": "assets/images/nature_009.webp"
    },
    {
      "id": "08",
      "photos": [
        "assets/images/nature_027.webp",
        "assets/images/nature_028.webp",
        "assets/images/nature_029.webp",
        "assets/images/nature_030.webp",
        "assets/images/nature_031.webp",
        "assets/images/nature_032.webp",
        "assets/images/nature_033.webp",
        "assets/images/nature_034.webp",
        "assets/images/nature_035.webp",
        "assets/images/nature_036.webp"
      ],
      "cover": "assets/images/nature_027.webp"
    },
    {
      "id": "02",
      "photos": [
        "assets/images/studio_001.webp",
        "assets/images/studio_002.webp",
        "assets/images/studio_003.webp",
        "assets/images/studio_004.webp",
        "assets/images/nature_001.webp",
        "assets/images/nature_002.webp",
        "assets/images/nature_003.webp",
        "assets/images/nature_004.webp",
        "assets/images/nature_005.webp",
        "assets/images/nature_006.webp",
        "assets/images/nature_007.webp",
        "assets/images/nature_008.webp"
      ],
      "cover": "assets/images/nature_001.webp"
    },
    {
      "id": "12",
      "photos": [
        "assets/images/kids_001.webp",
        "assets/images/kids_002.webp",
        "assets/images/kids_003.webp",
        "assets/images/kids_004.webp",
        "assets/images/kids_005.webp",
        "assets/images/kids_006.webp"
      ],
      "cover": "assets/images/kids_005.webp"
    }
  ],
  "genres": [
    {
      "slug": "nature",
      "name": "Природа",
      "photos": [
        "assets/images/nature_016.webp",
        "assets/images/nature_017.webp",
        "assets/images/nature_018.webp",
        "assets/images/nature_019.webp",
        "assets/images/nature_020.webp",
        "assets/images/nature_021.webp",
        "assets/images/nature_022.webp",
        "assets/images/nature_023.webp",
        "assets/images/nature_024.webp",
        "assets/images/nature_025.webp",
        "assets/images/nature_026.webp",
        "assets/images/nature_001.webp",
        "assets/images/nature_002.webp",
        "assets/images/nature_003.webp",
        "assets/images/nature_004.webp",
        "assets/images/nature_005.webp",
        "assets/images/nature_006.webp",
        "assets/images/nature_007.webp",
        "assets/images/nature_008.webp",
        "assets/images/nature_009.webp",
        "assets/images/nature_010.webp",
        "assets/images/nature_011.webp",
        "assets/images/nature_012.webp",
        "assets/images/nature_013.webp",
        "assets/images/nature_014.webp",
        "assets/images/nature_015.webp",
        "assets/images/nature_027.webp",
        "assets/images/nature_028.webp",
        "assets/images/nature_029.webp",
        "assets/images/nature_030.webp",
        "assets/images/nature_031.webp",
        "assets/images/nature_032.webp",
        "assets/images/nature_033.webp",
        "assets/images/nature_034.webp",
        "assets/images/nature_035.webp",
        "assets/images/nature_036.webp"
      ],
      "cover": "assets/covers/nature_cover.webp"
    },
    {
      "slug": "city",
      "name": "Город и улица",
      "photos": [
        "assets/images/city_001.webp",
        "assets/images/city_002.webp",
        "assets/images/city_003.webp",
        "assets/images/city_004.webp",
        "assets/images/city_005.webp",
        "assets/images/city_006.webp",
        "assets/images/city_007.webp",
        "assets/images/city_008.webp",
        "assets/images/city_009.webp",
        "assets/images/city_010.webp",
        "assets/images/city_011.webp"
      ],
      "cover": "assets/covers/city_cover.webp"
    },
    {
      "slug": "studio",
      "name": "Фотостудия и интерьер",
      "photos": [
        "assets/images/studio_015.webp",
        "assets/images/studio_016.webp",
        "assets/images/studio_017.webp",
        "assets/images/studio_018.webp",
        "assets/images/studio_019.webp",
        "assets/images/studio_020.webp",
        "assets/images/studio_021.webp",
        "assets/images/studio_022.webp",
        "assets/images/studio_023.webp",
        "assets/images/studio_024.webp",
        "assets/images/studio_025.webp",
        "assets/images/studio_026.webp",
        "assets/images/studio_027.webp",
        "assets/images/studio_028.webp",
        "assets/images/studio_029.webp",
        "assets/images/studio_030.webp",
        "assets/images/studio_031.webp",
        "assets/images/studio_032.webp",
        "assets/images/studio_033.webp",
        "assets/images/studio_034.webp",
        "assets/images/studio_005.webp",
        "assets/images/studio_006.webp",
        "assets/images/studio_007.webp",
        "assets/images/studio_008.webp",
        "assets/images/studio_009.webp",
        "assets/images/studio_010.webp",
        "assets/images/studio_011.webp",
        "assets/images/studio_012.webp",
        "assets/images/studio_013.webp",
        "assets/images/studio_014.webp",
        "assets/images/studio_001.webp",
        "assets/images/studio_002.webp",
        "assets/images/studio_003.webp",
        "assets/images/studio_004.webp"
      ],
      "cover": "assets/covers/studio_cover.webp"
    },
    {
      "slug": "reportage",
      "name": "Репортаж и концерт",
      "photos": [
        "assets/images/reportage_001.webp",
        "assets/images/reportage_002.webp",
        "assets/images/reportage_003.webp",
        "assets/images/reportage_004.webp"
      ],
      "cover": "assets/covers/reportage_cover.webp"
    },
    {
      "slug": "kids",
      "name": "Дети",
      "photos": [
        "assets/images/kids_001.webp",
        "assets/images/kids_002.webp",
        "assets/images/kids_003.webp",
        "assets/images/kids_004.webp",
        "assets/images/kids_005.webp",
        "assets/images/kids_006.webp"
      ],
      "cover": "assets/covers/kids_cover.webp"
    },
    {
      "slug": "love",
      "name": "Love Story",
      "photos": [
        "assets/images/love_001.webp",
        "assets/images/love_002.webp",
        "assets/images/love_003.webp"
      ],
      "cover": "assets/covers/love_cover.webp"
    }
  ],
  "background": [
    "assets/images/studio_015.webp",
    "assets/images/studio_016.webp",
    "assets/images/studio_017.webp",
    "assets/images/studio_018.webp",
    "assets/images/studio_019.webp",
    "assets/images/studio_020.webp",
    "assets/images/studio_021.webp",
    "assets/images/studio_022.webp",
    "assets/images/studio_023.webp",
    "assets/images/studio_024.webp",
    "assets/images/studio_025.webp",
    "assets/images/studio_026.webp",
    "assets/images/studio_027.webp",
    "assets/images/studio_028.webp",
    "assets/images/studio_029.webp",
    "assets/images/studio_030.webp",
    "assets/images/studio_031.webp",
    "assets/images/studio_032.webp",
    "assets/images/studio_033.webp",
    "assets/images/studio_034.webp",
    "assets/images/nature_016.webp",
    "assets/images/nature_017.webp",
    "assets/images/nature_018.webp",
    "assets/images/nature_019.webp",
    "assets/images/nature_020.webp",
    "assets/images/nature_021.webp",
    "assets/images/nature_022.webp",
    "assets/images/nature_023.webp",
    "assets/images/nature_024.webp",
    "assets/images/nature_025.webp",
    "assets/images/nature_026.webp",
    "assets/images/studio_005.webp",
    "assets/images/studio_006.webp",
    "assets/images/studio_007.webp",
    "assets/images/studio_008.webp",
    "assets/images/studio_009.webp",
    "assets/images/studio_010.webp",
    "assets/images/studio_011.webp",
    "assets/images/studio_012.webp",
    "assets/images/studio_013.webp",
    "assets/images/studio_014.webp",
    "assets/images/nature_001.webp",
    "assets/images/nature_002.webp",
    "assets/images/nature_003.webp",
    "assets/images/nature_004.webp",
    "assets/images/nature_005.webp",
    "assets/images/nature_006.webp",
    "assets/images/nature_007.webp",
    "assets/images/nature_008.webp",
    "assets/images/nature_009.webp",
    "assets/images/nature_010.webp",
    "assets/images/nature_011.webp",
    "assets/images/nature_012.webp",
    "assets/images/nature_013.webp",
    "assets/images/nature_014.webp",
    "assets/images/nature_015.webp",
    "assets/images/nature_027.webp",
    "assets/images/nature_028.webp",
    "assets/images/nature_029.webp",
    "assets/images/nature_030.webp",
    "assets/images/nature_031.webp",
    "assets/images/nature_032.webp",
    "assets/images/nature_033.webp",
    "assets/images/nature_034.webp",
    "assets/images/nature_035.webp",
    "assets/images/nature_036.webp",
    "assets/images/city_001.webp",
    "assets/images/city_002.webp",
    "assets/images/city_003.webp",
    "assets/images/city_004.webp",
    "assets/images/city_005.webp",
    "assets/images/city_006.webp",
    "assets/images/city_007.webp",
    "assets/images/city_008.webp",
    "assets/images/city_009.webp",
    "assets/images/city_010.webp",
    "assets/images/city_011.webp",
    "assets/images/studio_001.webp",
    "assets/images/studio_002.webp",
    "assets/images/studio_003.webp",
    "assets/images/studio_004.webp",
    "assets/images/love_001.webp",
    "assets/images/love_002.webp",
    "assets/images/love_003.webp",
    "assets/images/reportage_001.webp",
    "assets/images/reportage_002.webp",
    "assets/images/reportage_003.webp",
    "assets/images/reportage_004.webp",
    "assets/images/kids_001.webp",
    "assets/images/kids_002.webp",
    "assets/images/kids_003.webp"
  ]
};
